"""initial schema

Revision ID: d3e4bd1c3b88
Revises: 
Create Date: 2026-09-29 14:36:40.962080

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd3e4bd1c3b88'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barangay', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupants', sa.Integer(), nullable=True),
    sa.Column('facilities', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuation_centers_barangay'), 'evacuation_centers', ['barangay'], unique=False)
    op.create_index(op.f('ix_evacuation_centers_id'), 'evacuation_centers', ['id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_no', sa.String(), nullable=False),
    sa.Column('head_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('barangay', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('elderly_count', sa.Integer(), nullable=True),
    sa.Column('pwd_count', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_barangay'), 'households', ['barangay'], unique=False)
    op.create_index(op.f('ix_households_household_no'), 'households', ['household_no'], unique=True)
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('barangay', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('affected_households', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('reported_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_barangay'), 'incidents', ['barangay'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('stored_in', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_barangay'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_index(op.f('ix_households_household_no'), table_name='households')
    op.drop_index(op.f('ix_households_barangay'), table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_evacuation_centers_id'), table_name='evacuation_centers')
    op.drop_index(op.f('ix_evacuation_centers_barangay'), table_name='evacuation_centers')
    op.drop_table('evacuation_centers')
    # ### end Alembic commands ###
