"""resource transactions, evacuation assignments, incident zone geometry

Revision ID: dc12f28c2e06
Revises: d3e4bd1c3b88
Create Date: 2026-09-29 14:38:29.715257

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dc12f28c2e06'
down_revision: str | None = 'd3e4bd1c3b88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('occupants', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['evacuation_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuation_assignments_assigned_at'), 'evacuation_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_evacuation_assignments_center_id'), 'evacuation_assignments', ['center_id'], unique=False)
    op.create_index(op.f('ix_evacuation_assignments_household_id'), 'evacuation_assignments', ['household_id'], unique=False)
    op.create_index(op.f('ix_evacuation_assignments_id'), 'evacuation_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_evacuation_assignments_request_id'), 'evacuation_assignments', ['request_id'], unique=False)
    op.create_table('resource_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_transactions_created_at'), 'resource_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_resource_transactions_id'), 'resource_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_resource_transactions_resource_id'), 'resource_transactions', ['resource_id'], unique=False)
    op.add_column('incidents', sa.Column('zone_geojson', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'zone_geojson')
    op.drop_index(op.f('ix_resource_transactions_resource_id'), table_name='resource_transactions')
    op.drop_index(op.f('ix_resource_transactions_id'), table_name='resource_transactions')
    op.drop_index(op.f('ix_resource_transactions_created_at'), table_name='resource_transactions')
    op.drop_table('resource_transactions')
    op.drop_index(op.f('ix_evacuation_assignments_request_id'), table_name='evacuation_assignments')
    op.drop_index(op.f('ix_evacuation_assignments_id'), table_name='evacuation_assignments')
    op.drop_index(op.f('ix_evacuation_assignments_household_id'), table_name='evacuation_assignments')
    op.drop_index(op.f('ix_evacuation_assignments_center_id'), table_name='evacuation_assignments')
    op.drop_index(op.f('ix_evacuation_assignments_assigned_at'), table_name='evacuation_assignments')
    op.drop_table('evacuation_assignments')
    # ### end Alembic commands ###
