"""initial schema

Revision ID: 8ebd5a148d1c
Revises: 
Create Date: 2026-09-24 07:31:05.425795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebd5a148d1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evacuation_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('barangay', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupants', sa.Integer(), nullable=False),
    sa.Column('facilities', sa.JSON(), nullable=False),
    sa.Column('contact', sa.String(length=40), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evacuation_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evacuation_centers_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_centers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_centers_status'), ['status'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_no', sa.String(length=40), nullable=False),
    sa.Column('head_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('barangay', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('children_count', sa.Integer(), nullable=False),
    sa.Column('elderly_count', sa.Integer(), nullable=False),
    sa.Column('pwd_count', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=40), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_head_name'), ['head_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_household_no'), ['household_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_households_id'), ['id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('barangay', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('affected_households', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=True),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_barangay'), ['barangay'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_type'), ['type'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('stored_in', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_type'), ['type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('evacuation_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['evacuation_centers.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evacuation_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evacuation_assignments_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evacuation_assignments_request_id'), ['request_id'], unique=False)

    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transactions_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transactions_resource_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transactions_id'))

    op.drop_table('stock_transactions')
    with op.batch_alter_table('evacuation_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evacuation_assignments_request_id'))
        batch_op.drop_index(batch_op.f('ix_evacuation_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_evacuation_assignments_household_id'))

    op.drop_table('evacuation_assignments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_type'))
        batch_op.drop_index(batch_op.f('ix_resources_id'))

    op.drop_table('resources')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_barangay'))

    op.drop_table('incidents')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_id'))
        batch_op.drop_index(batch_op.f('ix_households_household_no'))
        batch_op.drop_index(batch_op.f('ix_households_head_name'))
        batch_op.drop_index(batch_op.f('ix_households_barangay'))

    op.drop_table('households')
    with op.batch_alter_table('evacuation_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evacuation_centers_status'))
        batch_op.drop_index(batch_op.f('ix_evacuation_centers_id'))
        batch_op.drop_index(batch_op.f('ix_evacuation_centers_barangay'))

    op.drop_table('evacuation_centers')
    # ### end Alembic commands ###
