SAN_RAFAEL_BARANGAYS = [
    "Balagtas",
    "Banca-banca",
    "Caingin",
    "Coral na Bato",
    "Cruz na Daan",
    "Dagat-dagatan",
    "Diliman I",
    "Diliman II",
    "Capihan",
    "Libis",
    "Lico",
    "Maasim",
    "Mabalas-balas",
    "Maguinao",
    "Maronquillo",
    "Paco",
    "Pansumaloc",
    "Pantubig",
    "Pasong Bangkal",
    "Pasong Callos",
    "Pasong Intsik",
    "Pinacpinacan",
    "Poblacion",
    "Pulo",
    "Pulong Bayabas",
    "Salapungan",
    "Sampaloc",
    "San Agustin",
    "San Roque",
    "Talacsan",
    "Tambubong",
    "Tukod",
    "Ulingao",
    "Sapang Pahalang",
]
